"""Write every published table to bench/results/ as markdown.

    uv run python scripts/matrix.py

The README pastes these tables with a run date; rerun this after any change to
the corpus, the victim or a defense, and replace stale numbers.
"""

from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

from chakravyuh.bench import run_all  # noqa: E402


def main() -> int:
    out_dir = Path(__file__).resolve().parent.parent / "bench" / "results"
    out_dir.mkdir(parents=True, exist_ok=True)

    report = run_all(reps=3)
    header = (
        f"<!-- generated by scripts/matrix.py on {date.today().isoformat()}, "
        f"victim {report.headline['victim']} -->\n\n"
    )
    (out_dir / "chakravyuh.md").write_text(
        header + "\n\n".join(report.sections) + "\n", encoding="utf-8"
    )
    print(f"wrote {out_dir / 'chakravyuh.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
